version: '3.1'

services:

  redis:
    build: .
    container_name: redis
    restart: always
    environment:
      redis_port: '6379'
    tty: true
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "6379:6379"
    volumes:
      - ./data/:/data/:rw
    networks:
      - zhl-es

networks:
  zhl-es:
    external: true